# Generated by Django 3.2 on 2021-11-18 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_auto_20200608_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_cat',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_publish_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
        ),
    ]
